### ISSUE TITLE
[Feature] opencv-contrib modules

### ISSUE THREAD

**Issue by cocoa-xu** [cocoa-xu/evision#140]
I plan to add support for modules in [`opencv_contrib`](https://github.com/opencv/opencv_contrib) gradually. Of course, this would bring an inevitable question: **not everyone will use modules in `opencv_contrib`, so including them in the precompiled binaries will increase the footprint.**

Will it be feasible to have an `:evision_contrib` library in Elixir (like its python counterpart, where we have `opencv-python` and `opencv-python-contrib`)?

### Modules (part 1)
- [x] barcode
- [x] dnn_superres
- [x] face
- [x] img_hash
- [x] plot
- [x] quality
- [x] rapid
- [x] sfm
- [x] shape
- [x] structured_light
- [x] text
- [x] tracking
- [x] xfeatures2d
- [x] ximgproc
- [x] xphoto

### Modules (part 2)
- [x] aruco
- [x] bgsegm
- [x] bioinspired
- [x] hfs
- [x] line_descriptor
- [x] mcc
- [x] reg
- [x] rgbd
- [x] saliency
- [x] stereo
- [x] surface_matching
- [x] wechat_qrcode

### Modules (part 3)
- [x] cudaarithm
- [x] cudabgsegm
- [x] cudacodec
- [x] cudafeatures2d
- [x] cudafilters
- [x] cudaimgproc
- [x] cudalegacy
- [x] cudaobjdetect
- [x] cudaoptflow
- [x] cudastereo
- [x] cudawarping
- [x] cudev

### todo
- [x] Check module name and struct name
- [x] Check `_Params` classes
- [ ] #172

**Comment by cocoa-xu** [comment]
module `hdf` and `freetype` in the opencv_contrib will not include in the precompiled binaries because they depend on external libraries.

Nevertheless, it's possible to compile libhdf5 and ship it together.

**Comment by cocoa-xu** [comment]
There are several ways we can take:

- Including both `opencv` and `opencv_contrib` in the precompiled binaries.
- Using an environment variable to indicate whether to include `opencv_contrib` (both for precompilation and compiling from source).

**Comment by cocoa-xu** [comment]
### todo
- [ ] Check module name and struct name
- [ ] Check `_Params` classes

**Comment by cocoa-xu** [comment]
Some issues in v0.1.26-rc2. The name of these modules needs to be corrected.

- https://hexdocs.pm/evision/0.1.26-rc2/Evision.Ximgprocsegmentation.html
- https://hexdocs.pm/evision/0.1.26-rc2/Evision.Utilsnested.html

**Comment by cocoa-xu** [comment]
v0.1.26 is shipped. I'll add examples and tests later!
